#!/bin/sh
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}
DAYON_HOME=$(dirname "$(realpath "$0")")
if which java >/dev/null; then
  JAVA=$(which java)
else
  JAVA_HOME=$(/usr/libexec/java_home)
  JAVA=${JAVA_HOME}/bin/java
fi
JAVA_OPTS=
CLASSPATH=${DAYON_HOME}/dayon.jar
${JAVA} ${JAVA_OPTS} -Ddayon.log=file -cp "${CLASSPATH}" "$@"
