#!/bin/sh
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}
ABS_PATH=$(dirname $(realpath "$0"))
if [ ! -f "$ABS_PATH/dayon" ]; then
  "$ABS_PATH/dayon/dayon" mpo.dayon.assisted.AssistedRunner $1 $2 $3
else
  "$ABS_PATH/dayon" mpo.dayon.assisted.AssistedRunner $1 $2 $3
fi