#!/bin/sh -e

case "$1" in
        purge|remove)
                if [ -f "/usr/local/bin/dayon.sh" ]; then
                    rm "/usr/local/bin/dayon*"
                fi
        ;;
        upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
        *)
                echo "$0 called with unknown argument \`$1'" >&2
                exit 1
        ;;
esac

rm -f /usr/share/applications/dayon_assistant.desktop
rm -f /usr/share/applications/dayon_assisted.desktop
