name: dayon
title: Dayon!
adopt-info: dayon
summary: An easy-to-use, cross-platform remote desktop assistance solution
description: |
  An easy-to-use, cross-platform remote desktop support solution for everyone.
  It can be used as free alternative to various commercial remote desktop and remote assistance products.
  Its key features are
  - no router or network configuration required on the assisted side
  - friendly, multilingual (de/en/es/fr/it/ru/tr/zh) user interface
  - assistant and assisted functionality in one package
  - secure, end-to-end encrypted communication (TLS 1.3)
license: GPL-3.0
grade: stable
base: core22
confinement: strict

lint:
  ignore:
    - library:
        - usr/lib/jvm/java-*/lib/*.so

apps:
  assisted:
    extensions:
      [gnome-3-28]
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-$SNAP_ARCH
      PATH: $JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH
    command: bin/dayon.launcher $SNAP/jar/dayon.jar $1 $2 $3 $4 $5
    desktop: ../parts/dayon/build/target/dayon.assisted.desktop
    plugs:
      [home, network, network-bind, desktop]

  assistant:
    extensions:
      [gnome-3-28]
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-$SNAP_ARCH
      PATH: $JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH
    command: bin/dayon.launcher $SNAP/jar/dayon.jar assistant $1 $2 $3
    desktop: ../parts/dayon/build/target/dayon.assistant.desktop
    plugs:
      [home, network, network-bind, desktop]

  browser:
    extensions:
      [gnome-3-28]
    command: bin/dayon.browser
    plugs:
      [home, network, desktop]

parts:
  dayon:
    plugin: maven
    source: https://github.com/retgal/dayon.git
    source-tag: master
    source-type: git
    maven-parameters:
      [-Psnap]

    build-packages:
      - openjdk-11-jdk
      - maven

    override-build: |
      craftctl default
      cp target/dayon.browser $CRAFT_PART_INSTALL/bin/
      cp target/dayon.launcher $CRAFT_PART_INSTALL/bin/
      cp target/dayon.png $CRAFT_PART_INSTALL/bin/
      rm $CRAFT_PART_INSTALL/jar/original-dayon.jar

    stage-packages:
      [openjdk-11-jre]
