name: dayon
title: Dayon!
adopt-info: dayon
summary: An easy-to-use, cross-platform remote desktop assistance solution
description: |
  An easy-to-use, cross-platform remote desktop support solution for everyone.
  It can be used as free alternative to various commercial remote desktop and remote assistance products.
  Its key features are
  - no router or network configuration required on the assisted side
  - friendly, multilingual (de/en/es/fr/it/ru/tr/zh) user interface
  - assistant and assisted functionality in one package
  - secure, encrypted communication (TLS)
license: GPL-3.0
grade: stable
base: core18
confinement: strict

apps:
  assisted:
    extensions:
      [gnome-3-28]
    command: bin/dayon.launcher $SNAP/jar/dayon.jar mpo.dayon.assisted.AssistedRunner $1 $2 $3 $4
    desktop: ../parts/dayon/build/target/dayon.assisted.desktop
    plugs:
      [home, network, network-bind, desktop]

  assistant:
    extensions:
      [gnome-3-28]
    command: bin/dayon.launcher $SNAP/jar/dayon.jar mpo.dayon.assistant.AssistantRunner $1 $2
    desktop: ../parts/dayon/build/target/dayon.assistant.desktop
    plugs:
      [home, network, network-bind, desktop]

  browser:
    extensions:
      [gnome-3-28]
    command: bin/dayon.browser
    plugs:
      [home, network, desktop]

parts:
  dayon:
    plugin: maven
    source: https://github.com/retgal/dayon.git
    source-tag: master
    source-type: git
    maven-options:
      [-Psnap]
    
    build-packages:
      [default-jre]
   
    override-build: |
      snapcraftctl build
      cp target/dayon.browser $SNAPCRAFT_PART_INSTALL/bin/
      cp target/dayon.launcher $SNAPCRAFT_PART_INSTALL/bin/
      cp target/dayon.png $SNAPCRAFT_PART_INSTALL/bin/
      
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      
    filesets:
      exclude-original-jar:
        [-jar/original-dayon.jar]
    
    stage:
      [$exclude-original-jar]
      
    stage-packages:
      [default-jre]

    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
